# Generated by Django 3.1.1 on 2020-10-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='company',
        ),
        migrations.RemoveField(
            model_name='device',
            name='iotdevnum',
        ),
        migrations.AddField(
            model_name='device',
            name='Inactivedate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备不活动日期'),
        ),
        migrations.AddField(
            model_name='device',
            name='Installdate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备安装日期'),
        ),
        migrations.AddField(
            model_name='device',
            name='alrdepreciation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备折旧已提足'),
        ),
        migrations.AddField(
            model_name='device',
            name='apcbusiness',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='APC业务'),
        ),
        migrations.AddField(
            model_name='device',
            name='bindingdate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备绑定日期'),
        ),
        migrations.AddField(
            model_name='device',
            name='cncphotos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备图片'),
        ),
        migrations.AddField(
            model_name='device',
            name='cncserialnum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备序列号'),
        ),
        migrations.AddField(
            model_name='device',
            name='costcenter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备成本中心'),
        ),
        migrations.AddField(
            model_name='device',
            name='costdescription',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备成本中心描述'),
        ),
        migrations.AddField(
            model_name='device',
            name='depreciationcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备折旧码'),
        ),
        migrations.AddField(
            model_name='device',
            name='depreciationcount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备累计折旧'),
        ),
        migrations.AddField(
            model_name='device',
            name='devbookvalue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备账面价值'),
        ),
        migrations.AddField(
            model_name='device',
            name='devcompany',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备所属公司'),
        ),
        migrations.AddField(
            model_name='device',
            name='devdepreciation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备本年折旧'),
        ),
        migrations.AddField(
            model_name='device',
            name='devimpairment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备减值准备'),
        ),
        migrations.AddField(
            model_name='device',
            name='devperiod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备折旧期限'),
        ),
        migrations.AddField(
            model_name='device',
            name='estimatedresidual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备预计残值额'),
        ),
        migrations.AddField(
            model_name='device',
            name='formerdepreciation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备往年折旧'),
        ),
        migrations.AddField(
            model_name='device',
            name='machintype',
            field=models.CharField(max_length=50, null=True, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='device',
            name='monthdepreciation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备本月折旧'),
        ),
        migrations.AddField(
            model_name='device',
            name='plandepreciation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备计划折旧年'),
        ),
        migrations.AddField(
            model_name='device',
            name='purchasevalue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备购置价值'),
        ),
        migrations.AddField(
            model_name='device',
            name='residualrate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备残值率'),
        ),
        migrations.AddField(
            model_name='device',
            name='residualvalue',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备残值'),
        ),
        migrations.AddField(
            model_name='device',
            name='stardata',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备折旧开始日'),
        ),
        migrations.AddField(
            model_name='device',
            name='validperiod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='超过有效期'),
        ),
        migrations.AddField(
            model_name='device',
            name='warrantydate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备质保日期'),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AbsolutePositionu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AbsolutePositionw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AbsolutePositionx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AbsolutePositiony',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AbsolutePositionz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AlarmState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_AvailableProgramCount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_CncPmcType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_CurrentProgramProcessTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_CutTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_EffectiveAxeCount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_EmergencyStopStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ErrorMessage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_FeedSpeed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_LifeTimer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_MachineName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ManufacturerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_PowerOnTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ProgramDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_RegisteredProgramCount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_RunningTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_SingleProcessCount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_SpindleLoad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_SpindleSpeed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ToolCompensationValue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ToolSetCount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_ToolSetNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_UnusedMemory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='FANUC_UsedMemory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='cncsystemtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='distanceposu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='distanceposw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='effectiveaxes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='errorlevelalarms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='fastmagnification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='feedprogrammingspeed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='handwheeloverride',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='machineposu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='machineposw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='manualoverride',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='programinformation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='programsize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='relativeposu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='relativeposw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='spindleprogrammingspeed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuju',
            name='warninglevelalarms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='cncstate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='departmentwork',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备部门车间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devclass',
            field=models.CharField(max_length=50, null=True, verbose_name='设备分类'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devname',
            field=models.CharField(max_length=50, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devnum',
            field=models.CharField(max_length=50, null=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOT设备编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='installer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOT设备安装人员'),
        ),
        migrations.AlterField(
            model_name='device',
            name='iotstate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOT设备状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='isconiot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='是否接入物联网'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='设备制造商'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturernum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='厂家编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sensornumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOT设备传感器数量'),
        ),
    ]
