# Generated by Django 3.1.1 on 2020-11-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201107_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='菜单名称')),
                ('level', models.IntegerField(max_length=1, null=True, verbose_name='菜单级别')),
                ('lable', models.CharField(max_length=20, null=True, verbose_name='标签')),
                ('path', models.CharField(max_length=100, null=True, verbose_name='路由')),
                ('component', models.CharField(max_length=20, null=True, verbose_name='组件')),
                ('icon', models.CharField(max_length=20, null=True, verbose_name='图标')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
            options={
                'unique_together': {('userinfo', 'menu')},
            },
        ),
    ]
