# Generated by Django 3.1.1 on 2020-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201111_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
