# Generated by Django 3.1.1 on 2020-11-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='iotmac',
            field=models.CharField(max_length=50, null=True, verbose_name='iot的mac地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='iotmanufacturernum',
            field=models.CharField(max_length=50, null=True, verbose_name='iot厂家编号'),
        ),
        migrations.AddField(
            model_name='device',
            name='simnum',
            field=models.CharField(max_length=50, null=True, verbose_name='sim卡号'),
        ),
    ]
