from django.db import models

# Create your models here.
class Company(models.Model):
    company=models.CharField(max_length=50,null=True)
    creditnum=models.CharField(max_length=50,null=True)
    contactperson=models.CharField(max_length=20,null=True)
    telephone=models.CharField(max_length=20,null=True)
    comprovince=models.CharField(max_length=20,null=True)
    comaddress=models.CharField(max_length=50,null=True)

class Department(models.Model):
    department=models.CharField(max_length=50,null=True)
    company=models.ForeignKey("Company",on_delete=models.CASCADE)


class UserInfo(models.Model):
    accountnum=models.CharField(max_length=50,null=True)
    password=models.CharField(max_length=50,null=True)
    username=models.CharField(max_length=50,null=True)
    department=models.CharField(max_length=20,null=True)
    company=models.CharField(max_length=50,null=True)
    jobnum=models.CharField(max_length=30,null=True)
    phonenum=models.CharField(max_length=50,null=True)
    email=models.CharField(max_length=30,null=True)
    province=models.CharField(max_length=20,null=True)
    address=models.CharField(max_length=50,null=True)
    usercode=models.CharField(max_length=50,null=True)
    userrole=models.CharField(max_length=50,null=True)
    category=models.CharField(max_length=20,null=True)
    level=models.CharField(max_length=20,null=True)
    avatar=models.CharField(max_length=100,null=True)



class Menu(models.Model):
    name=models.CharField(verbose_name='菜单名称',max_length=20,null=True)
    level=models.IntegerField(verbose_name='菜单级别',null=True)
    parent=models.ForeignKey('self',related_name='subs',null=True,blank=True,on_delete=models.CASCADE)
    lable=models.CharField(verbose_name='标签',max_length=20,null=True)
    path=models.CharField(verbose_name='路由',max_length=100,null=True)
    component=models.CharField(verbose_name='组件',max_length=20,null=True)
    icon=models.CharField(verbose_name='图标',max_length=20,null=True)
    hidden=models.BooleanField(verbose_name='是否隐藏',default=False)

class UserInfo_Menu(models.Model):
    userinfo=models.ForeignKey('UserInfo',on_delete=models.CASCADE)
    menu=models.ForeignKey('Menu',on_delete=models.CASCADE)

    class Meta:
        unique_together=[('userinfo','menu'),]





class Device(models.Model):
    devnum=models.CharField(verbose_name='资产编号',max_length=50,null=True)
    devclass=models.CharField(verbose_name='设备分类',max_length=50,null=True)
    machintype=models.CharField(verbose_name='设备型号',max_length=50,null=True)
    devname=models.CharField(verbose_name='设备名称',max_length=50,null=True)
    departmentwork=models.CharField(verbose_name='设备部门车间',max_length=50,null=True,blank=True)
    manufacturernum=models.CharField(verbose_name='厂家编号',max_length=50,null=True,blank=True)
    manufacturer=models.CharField(verbose_name='设备制造商',max_length=60,null=True,blank=True)
    cncserialnum=models.CharField(verbose_name='设备序列号',max_length=50,null=True,blank=True)
    cncstate=models.CharField(verbose_name='设备状态',max_length=50,null=True,blank=True)
    isconiot=models.CharField(verbose_name='是否接入物联网',max_length=50,null=True,blank=True)
    Installdate=models.CharField(verbose_name='设备安装日期',max_length=50,null=True,blank=True)
    bindingdate=models.CharField(verbose_name='设备绑定日期',max_length=50,null=True,blank=True)
    warrantydate=models.CharField(verbose_name='设备质保日期',max_length=50,null=True,blank=True)
    stardata=models.CharField(verbose_name='设备折旧开始日',max_length=50,null=True,blank=True)
    Inactivedate=models.CharField(verbose_name='设备不活动日期',max_length=50,null=True,blank=True)
    devperiod=models.CharField(verbose_name='设备折旧期限',max_length=50,null=True,blank=True)
    purchasevalue=models.CharField(verbose_name='设备购置价值',max_length=50,null=True,blank=True)
    devimpairment=models.CharField(verbose_name='设备减值准备',max_length=50,null=True,blank=True)
    devdepreciation=models.CharField(verbose_name='设备本年折旧',max_length=50,null=True,blank=True)
    formerdepreciation=models.CharField(verbose_name='设备往年折旧',max_length=50,null=True,blank=True)
    depreciationcount=models.CharField(verbose_name='设备累计折旧',max_length=50,null=True,blank=True)
    devbookvalue=models.CharField(verbose_name='设备账面价值',max_length=50,null=True,blank=True)
    monthdepreciation=models.CharField(verbose_name='设备本月折旧',max_length=50,null=True,blank=True)
    alrdepreciation=models.CharField(verbose_name='设备折旧已提足',max_length=50,null=True,blank=True)
    costcenter=models.CharField(verbose_name='设备成本中心',max_length=50,null=True,blank=True)
    costdescription=models.CharField(verbose_name='设备成本中心描述',max_length=50,null=True,blank=True)
    residualrate=models.CharField(verbose_name='设备残值率',max_length=50,null=True,blank=True)
    residualvalue=models.CharField(verbose_name='设备残值',max_length=50,null=True,blank=True)
    estimatedresidual=models.CharField(verbose_name='设备预计残值额',max_length=50,null=True,blank=True)
    depreciationcode=models.CharField(verbose_name='设备折旧码',max_length=50,null=True,blank=True)
    plandepreciation=models.CharField(verbose_name='设备计划折旧年',max_length=50,null=True,blank=True)
    validperiod=models.CharField(verbose_name='超过有效期',max_length=50,null=True,blank=True)
    apcbusiness=models.CharField(verbose_name='APC业务',max_length=50,null=True,blank=True)
    cncphotos=models.CharField(verbose_name='设备图片',max_length=50,null=True,blank=True)
    devcompany=models.CharField(verbose_name='设备所属公司',max_length=50,null=True,blank=True)
    devip=models.CharField(verbose_name='设备IP',max_length=50,null=True,blank=True)
    devtype=models.CharField(verbose_name='IOT设备编号',max_length=50,null=True,blank=True)
    sensornumber=models.CharField(verbose_name='IOT设备传感器数量',max_length=50,null=True,blank=True)
    installer=models.CharField(verbose_name='IOT设备安装人员',max_length=50,null=True,blank=True)
    iotstate=models.CharField(verbose_name='IOT设备状态',max_length=50,null=True,blank=True)
    cameranum=models.CharField(verbose_name='摄像头设备号',max_length=50,null=True,blank=True)
    userinfo=models.ForeignKey("UserInfo",on_delete=models.CASCADE)
    iotmac=models.CharField(verbose_name='iot的mac地址',max_length=50,null=True)
    simnum=models.CharField(verbose_name='sim卡号',max_length=50,null=True)
    iotmanufacturernum=models.CharField(verbose_name='iot厂家编号',max_length=50,null=True)
    lastmaintendate=models.CharField(max_length=50,null=True)
    maintenancetime=models.CharField(max_length=50,null=True)
    maintenancemethod=models.CharField(max_length=50,null=True)
    maintainer=models.CharField(max_length=50,null=True)
    maintencontent=models.CharField(max_length=100,null=True)
    planmaindate=models.CharField(max_length=100,null=True)
    maintenancestatus=models.CharField(verbose_name='保养状态', max_length=50, null=True, blank=True)



class Shuju(models.Model):
    collecttime=models.DateTimeField(auto_now=True,auto_now_add=False)
    devtype=models.CharField(max_length=150,null=True)
    AICH0=models.CharField(max_length=150,null=True)
    AICH1=models.CharField(max_length=150,null=True)
    AICH2=models.CharField(max_length=150,null=True)
    AICH3=models.CharField(max_length=150,null=True)
    AICH4=models.CharField(max_length=150,null=True)
    AICH5=models.CharField(max_length=150,null=True)
    AICH6=models.CharField(max_length=150,null=True)
    AICH7=models.CharField(max_length=150,null=True)
    AICH8=models.CharField(max_length=150,null=True)
    AICH9=models.CharField(max_length=150,null=True)
    AICH10=models.CharField(max_length=150,null=True)
    AICH11=models.CharField(max_length=150,null=True)
    AICH12=models.CharField(max_length=150,null=True)
    AICH13=models.CharField(max_length=150,null=True)
    AICH14=models.CharField(max_length=150,null=True)
    AICH15=models.CharField(max_length=150,null=True)
    AICH16=models.CharField(max_length=150,null=True)
    AICH17=models.CharField(max_length=150,null=True)
    AICH18=models.CharField(max_length=150,null=True)
    AICH19=models.CharField(max_length=150,null=True)
    AICH20=models.CharField(max_length=150,null=True)
    AICH21=models.CharField(max_length=150,null=True)
    AICH22=models.CharField(max_length=150,null=True)
    AICH23=models.CharField(max_length=150,null=True)
    AICH24=models.CharField(max_length=150,null=True)
    AICH25=models.CharField(max_length=150,null=True)
    AICH26=models.CharField(max_length=150,null=True)
    AICH27=models.CharField(max_length=150,null=True)
    AICH28=models.CharField(max_length=150,null=True)
    AICH29=models.CharField(max_length=150,null=True)
    AICH30=models.CharField(max_length=150,null=True)
    AICH31=models.CharField(max_length=150,null=True)
    DOCH0=models.CharField(max_length=150,null=True)
    DOCH1=models.CharField(max_length=150,null=True)
    DOCH2=models.CharField(max_length=150,null=True)
    DOCH3=models.CharField(max_length=150,null=True)
    DOCH4=models.CharField(max_length=150,null=True)
    DOCH5=models.CharField(max_length=150,null=True)
    DOCH6=models.CharField(max_length=150,null=True)
    DOCH7=models.CharField(max_length=150,null=True)
    DOCH8=models.CharField(max_length=150,null=True)
    DOCH9=models.CharField(max_length=150,null=True)
    DOCH10=models.CharField(max_length=150,null=True)
    DOCH11=models.CharField(max_length=150,null=True)
    DOCH12=models.CharField(max_length=150,null=True)
    DOCH13=models.CharField(max_length=150,null=True)
    DOCH14=models.CharField(max_length=150,null=True)
    DOCH15=models.CharField(max_length=150,null=True)
    DOCH16=models.CharField(max_length=150,null=True)
    DOCH17=models.CharField(max_length=150,null=True)
    DOCH18=models.CharField(max_length=150,null=True)
    DOCH19=models.CharField(max_length=150,null=True)
    DOCH20=models.CharField(max_length=150,null=True)
    DOCH21=models.CharField(max_length=150,null=True)
    DOCH22=models.CharField(max_length=150,null=True)
    DOCH23=models.CharField(max_length=150,null=True)
    DOCH24=models.CharField(max_length=150,null=True)
    DOCH25=models.CharField(max_length=150,null=True)
    DOCH26=models.CharField(max_length=150,null=True)
    DOCH27=models.CharField(max_length=150,null=True)
    DOCH28=models.CharField(max_length=150,null=True)
    DOCH29=models.CharField(max_length=150,null=True)
    DOCH30=models.CharField(max_length=150,null=True)
    DOCH31=models.CharField(max_length=150,null=True)
    DOCH32=models.CharField(max_length=150,null=True)
    DOCH33=models.CharField(max_length=150,null=True)
    DOCH34=models.CharField(max_length=150,null=True)
    DICH0=models.CharField(max_length=150,null=True)
    DICH1=models.CharField(max_length=150,null=True)
    DICH2=models.CharField(max_length=150,null=True)
    DICH3=models.CharField(max_length=150,null=True)
    DICH4=models.CharField(max_length=150,null=True)
    DICH5=models.CharField(max_length=150,null=True)
    DICH6=models.CharField(max_length=150,null=True)
    DICH7=models.CharField(max_length=150,null=True)
    DICH8=models.CharField(max_length=150,null=True)
    DICH9=models.CharField(max_length=150,null=True)
    DICH10=models.CharField(max_length=150,null=True)
    DICH11=models.CharField(max_length=150,null=True)
    DICH12=models.CharField(max_length=150,null=True)
    DICH13=models.CharField(max_length=150,null=True)
    DICH14=models.CharField(max_length=150,null=True)
    DICH15=models.CharField(max_length=150,null=True)
    DICH16=models.CharField(max_length=150,null=True)
    DICH17=models.CharField(max_length=150,null=True)
    DICH18=models.CharField(max_length=150,null=True)
    DICH19=models.CharField(max_length=150,null=True)
    serialnum=models.CharField(max_length=150,null=True)
    versionnum=models.CharField(max_length=150,null=True)
    systemtype=models.CharField(max_length=100,null=True)
    voltage=models.CharField(max_length=100,null=True)
    current=models.CharField(max_length=100,null=True)
    power=models.CharField(max_length=100,null=True)
    temper=models.CharField(max_length=100,null=True)
    toolnum=models.CharField(max_length=100,null=True)
    toolpos=models.CharField(max_length=100,null=True)
    lengthnum=models.CharField(max_length=100,null=True)
    radiusnum=models.CharField(max_length=100,null=True)
    wearradius=models.CharField(max_length=100,null=True)
    lengthx=models.CharField(max_length=100,null=True)
    lengthz=models.CharField(max_length=100,null=True)
    feedspeedset=models.CharField(max_length=100,null=True)
    actualfeedspeed=models.CharField(max_length=100,null=True)
    spindlespeedset=models.CharField(max_length=100,null=True)
    actualspindlespeed=models.CharField(max_length=100,null=True)
    feedrate=models.CharField(max_length=100,null=True)
    spindlerate=models.CharField(max_length=100,null=True)
    spindlename=models.CharField(max_length=100,null=True)
    machineposx=models.CharField(max_length=100,null=True)
    machineposy=models.CharField(max_length=100,null=True)
    machineposz=models.CharField(max_length=100,null=True)
    machineposu=models.CharField(max_length=100,null=True)
    machineposw=models.CharField(max_length=100,null=True)
    relativeposx=models.CharField(max_length=100,null=True)
    relativeposy=models.CharField(max_length=100,null=True)
    relativeposz=models.CharField(max_length=100,null=True)
    relativeposu=models.CharField(max_length=100,null=True)
    relativeposw=models.CharField(max_length=100,null=True)
    distanceposx=models.CharField(max_length=100,null=True)
    distanceposy=models.CharField(max_length=100,null=True)
    distanceposz=models.CharField(max_length=100,null=True)
    distanceposu=models.CharField(max_length=100,null=True)
    distanceposw=models.CharField(max_length=100,null=True)
    FANUC_AbsolutePositionx=models.CharField(max_length=100,null=True)
    FANUC_AbsolutePositiony=models.CharField(max_length=100,null=True)
    FANUC_AbsolutePositionu=models.CharField(max_length=100,null=True)
    FANUC_AbsolutePositionw=models.CharField(max_length=100,null=True)
    FANUC_AbsolutePositionz=models.CharField(max_length=100,null=True)
    alarmnum=models.CharField(max_length=100,null=True)
    operationmode=models.CharField(max_length=100,null=True)
    runstate=models.CharField(max_length=100,null=True)
    programname=models.CharField(max_length=100,null=True)
    processingcode=models.CharField(max_length=100,null=True)
    processingcount=models.CharField(max_length=100,null=True)
    cycletime=models.CharField(max_length=100,null=True)
    rescuttingtime=models.CharField(max_length=100,null=True)
    parsing=models.CharField(max_length=100,null=True)
    powerontime=models.CharField(max_length=100,null=True)
    targetcount=models.CharField(max_length=100,null=True)
    alarmtime=models.CharField(max_length=100,null=True)
    DeviceConnect=models.CharField(max_length=100,null=True)
    FANUC_EmergencyStopStatus=models.CharField(max_length=100,null=True)
    FANUC_FeedSpeed=models.CharField(max_length=100,null=True)
    FANUC_SpindleSpeed=models.CharField(max_length=100,null=True)
    FANUC_EffectiveAxeCount=models.CharField(max_length=100,null=True)
    FANUC_SpindleLoad=models.CharField(max_length=100,null=True)
    FANUC_SingleProcessCount=models.CharField(max_length=100,null=True)
    FANUC_CutTime=models.CharField(max_length=100,null=True)
    FANUC_PowerOnTime=models.CharField(max_length=100,null=True)
    FANUC_RunningTime=models.CharField(max_length=100,null=True)
    FANUC_CurrentProgramProcessTime=models.CharField(max_length=100,null=True)
    FANUC_ManufacturerName=models.CharField(max_length=100,null=True)
    FANUC_MachineName=models.CharField(max_length=100,null=True)
    FANUC_CncPmcType=models.CharField(max_length=100,null=True)
    FANUC_ProgramDate=models.CharField(max_length=100,null=True)
    FANUC_AlarmState=models.CharField(max_length=100,null=True)
    FANUC_ToolSetCount=models.CharField(max_length=100,null=True)
    FANUC_ToolSetNumber=models.CharField(max_length=100,null=True)
    FANUC_LifeTimer=models.CharField(max_length=100,null=True)
    FANUC_ToolCompensationValue=models.CharField(max_length=100,null=True)
    FANUC_RegisteredProgramCount=models.CharField(max_length=100,null=True)
    FANUC_AvailableProgramCount=models.CharField(max_length=100,null=True)
    FANUC_UnusedMemory=models.CharField(max_length=100,null=True)
    FANUC_UsedMemory=models.CharField(max_length=100,null=True)
    FANUC_ErrorMessage=models.CharField(max_length=100,null=True)
    feedprogrammingspeed=models.CharField(max_length=50,null=True)
    spindleprogrammingspeed=models.CharField(max_length=50,null=True)
    fastmagnification=models.CharField(max_length=50,null=True)
    manualoverride=models.CharField(max_length=50,null=True)
    handwheeloverride=models.CharField(max_length=50,null=True)
    effectiveaxes=models.CharField(max_length=50,null=True)
    errorlevelalarms=models.CharField(max_length=50,null=True)
    warninglevelalarms=models.CharField(max_length=50,null=True)
    programsize=models.CharField(max_length=50,null=True)
    programinformation=models.CharField(max_length=50,null=True)
    cncsystemtype=models.CharField(max_length=100,null=True)


class Threshold(models.Model):
    temp1=models.CharField(max_length=20)
    temp2=models.CharField(max_length=20)
    temp3=models.CharField(max_length=20)
    vibration1=models.CharField(max_length=20)
    vibration2=models.CharField(max_length=20)
    vibration3=models.CharField(max_length=20)
    vibration4=models.CharField(max_length=20)
    current1=models.CharField(max_length=20)
    current2=models.CharField(max_length=20)
    current3=models.CharField(max_length=20)
    current4=models.CharField(max_length=20)
    power=models.CharField(max_length=20)
    AE1=models.CharField(max_length=20)
    AE2=models.CharField(max_length=20)
    res1=models.CharField(max_length=20)
    res2=models.CharField(max_length=20)
    res3=models.CharField(max_length=20)
    res4=models.CharField(max_length=20)
    res5=models.CharField(max_length=20)
    res6=models.CharField(max_length=20)
    res7=models.CharField(max_length=20)
    res8=models.CharField(max_length=20)
    res9=models.CharField(max_length=20)
    res10=models.CharField(max_length=20)
    res11=models.CharField(max_length=20)
    res12=models.CharField(max_length=20)
    res13=models.CharField(max_length=20)
    res14=models.CharField(max_length=20)
    res15=models.CharField(max_length=20)
    res16=models.CharField(max_length=20)
    res17=models.CharField(max_length=20)
    res18=models.CharField(max_length=20)


   
  

    



    